name: Frogbot Security Scan

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # Weekly full scan on Mondays

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Frogbot by JFrog
        uses: jfrog/frogbot@v2.28.0
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
