repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks

- repo: local
  hooks:
    # Rust-based Markdown/TOML/JSON formatting via dprint
    - id: dprint-fmt
      name: dprint fmt
      entry: dprint
      args: ["fmt", "--config", "dprint.json"]
      language: system
      pass_filenames: true
      types_or: [markdown, toml, json]

    # Rust-based shell linter/formatter (not a complete replacement for ShellCheck)
    - id: shellharden-check
      name: shellharden (lint)
      entry: shellharden
      args: ["--check"]
      language: system
      pass_filenames: true
      types: [shell]
