name: Code Quality and Security

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

env:
  RUST_TOOLCHAIN: stable

# Consolidated top-level permissions
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Scan - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Continue with other builds even if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Improved cache setup with newer action
      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/
          key: ${{ runner.os }}-rust-${{ env.RUST_TOOLCHAIN }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_TOOLCHAIN }}-
      
      # Clippy Analysis
      - name: Setup Rust tools
        run: |
          rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt --force
      
      - name: Run Clippy Analysis
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      
      - name: Upload Clippy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      # DevSkim Security Scan - only on Ubuntu
      - name: Run DevSkim scanner
        if: runner.os == 'Linux'
        uses: microsoft/DevSkim-Action@v1
      
      - name: Upload DevSkim scan results
        if: runner.os == 'Linux'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif

  osv-scanner:
    name: OSV Scanner
    runs-on: ubuntu-latest # Only need to run once
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run OSV Scanner
        uses: google/osv-scanner/actions/scanner@v1.8.2
        with:
          fail-on-vuln: false